mypy and flake8
google/budoux pull request #34
Opened 2022-01-11 16:35 UTC by eggplants

2022-01-11 22:46 UTC, eggplants commented
Type subscription in numpy (like `np.floating[typing.Any]`) is available on Python >=3.9.

2022-01-13 05:30 UTC, tushuhei requested changes
Thank you for a lot of improvements to make our code typed! Let me ask some minor fixes.

2022-01-13 05:30 UTC, tushuhei commented on scripts/train.py
> +    res: npt.NDArray[typing.Any] = w.dot(Y_train[:, None] ^ X_train) / w.sum()
Can we type this as `npt.NDArray[np.float64]`?

2022-01-13 09:34 UTC, tushuhei requested changes

2022-01-13 09:34 UTC, tushuhei commented on budoux/feature_extractor.py
> +  for datam in data:
nit: s/datam/datum

2022-01-13 09:38 UTC, tushuhei approved these changes
LGTM. Thank you so much!

2022-01-13 09:39 UTC, merged